# Generated by Django 4.2.5 on 2025-03-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biometricdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('biometric_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometricdata.biometricdata')),
            ],
        ),
    ]
