# Generated by Django 4.2.5 on 2025-04-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPayroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_payroll', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_paydate', models.DateField(blank=True, null=True)),
                ('upcoming_payroll', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upcoming_paydate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
