# Generated by Django 4.2.5 on 2025-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCalendarPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_type', models.CharField(choices=[('payroll_period_start', 'Payroll Period Start'), ('payroll_period_end', 'Payroll Period End')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'date_type')},
            },
        ),
        migrations.CreateModel(
            name='MasterCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('regular', 'Regular Holiday'), ('special', 'Special Holiday')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'holiday_type')},
            },
        ),
    ]
