# Generated by Django 4.2.5 on 2025-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercalendarpayroll',
            options={'ordering': ['payroll_period_start', 'payroll_period_end']},
        ),
        migrations.AlterUniqueTogether(
            name='mastercalendarpayroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mastercalendarpayroll',
            name='payroll_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastercalendarpayroll',
            name='payroll_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mastercalendarpayroll',
            unique_together={('payroll_period_start', 'payroll_period_end')},
        ),
        migrations.RemoveField(
            model_name='mastercalendarpayroll',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mastercalendarpayroll',
            name='date_type',
        ),
        migrations.RemoveField(
            model_name='mastercalendarpayroll',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mastercalendarpayroll',
            name='name',
        ),
    ]
