# Generated by Django 4.2.5 on 2025-03-24 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('philhealth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pagibig', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wtax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nowork', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('undertime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msfcloan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
