# Generated by Django 4.2.5 on 2025-03-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deductions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deductions',
            name='pagibig',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='philhealth',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='sss',
        ),
    ]
