# Generated by Django 4.2.5 on 2025-03-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deductions', '0002_remove_deductions_pagibig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deductions',
            name='late',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='undertime',
        ),
    ]
