# Generated by Django 4.2.5 on 2025-04-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment_info', '0003_employmentinfo_resignation_date'),
        ('payroll', '0002_payroll_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='employment_info_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment_info.employmentinfo'),
        ),
    ]
