# Generated by Django 4.2.5 on 2025-01-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
