# Generated by Django 4.2.5 on 2025-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='employmentinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentinfo',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employmentinfo',
            name='other_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmentinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
