# Generated by Django 4.2.5 on 2025-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_info', '0002_remove_employmentinfo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinfo',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
