# Generated by Django 4.2.5 on 2025-03-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('overtimehours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalOvertime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_regularot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_regularholiday', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_specialholiday', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_restday', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_nightdiff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_backwage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_overtime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtimehours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overtimehours.overtimehours')),
            ],
        ),
    ]
