# Generated by Django 4.2.5 on 2025-03-25 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('totalovertime', '0003_totalovertime_biweek_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalovertime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
