# Generated by Django 4.2.5 on 2025-03-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totalovertime', '0004_totalovertime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalovertime',
            name='overtimehours',
        ),
    ]
