# Generated by Django 4.2.5 on 2025-03-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalovertime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalovertime',
            name='total_late',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='totalovertime',
            name='total_undertime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalovertime',
            name='total_backwage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalovertime',
            name='total_nightdiff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalovertime',
            name='total_overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalovertime',
            name='total_regularholiday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalovertime',
            name='total_regularot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalovertime',
            name='total_restday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalovertime',
            name='total_specialholiday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
