# Generated by Django 4.2.5 on 2025-03-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalovertime', '0002_totalovertime_total_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalovertime',
            name='biweek_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
