# Generated by Django 4.2.5 on 2025-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalovertime', '0005_remove_totalovertime_overtimehours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalovertime',
            name='total_overtime',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
