# Generated by Django 4.2.5 on 2025-03-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('work_code', models.CharField(max_length=50)),
                ('work_state', models.CharField(max_length=50)),
                ('terminal_name', models.CharField(max_length=100)),
            ],
        ),
    ]
