# Generated by Django 4.2.5 on 2025-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometricdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdata',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
