# Generated by Django 4.2.5 on 2025-03-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometricdata', '0002_alter_biometricdata_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricdata',
            name='user_id',
        ),
    ]
