# Generated by Django 4.2.5 on 2025-04-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_summary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtimehours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimehours',
            name='attendancesummary_id',
        ),
        migrations.AddField(
            model_name='overtimehours',
            name='attendancesummary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_summary.attendancesummary'),
        ),
        migrations.AddField(
            model_name='overtimehours',
            name='biweek_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimehours',
            name='late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overtimehours',
            name='undertime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overtimehours',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='backwage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='nightdiff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='regularholiday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='regularot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='restday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='specialholiday',
            field=models.IntegerField(default=0),
        ),
    ]
