# Generated by Django 4.2.5 on 2025-04-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimehours', '0002_remove_overtimehours_attendancesummary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimehours',
            name='actualhours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
