# Generated by Django 4.2.5 on 2025-03-30 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employer_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ec_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employer_mpf_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee_mpf_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_employer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_employee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Philhealth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagibig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employer_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
