# Generated by Django 4.2.5 on 2025-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='restday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
