# Generated by Django 4.2.5 on 2025-04-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_restday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='payroll_period',
        ),
        migrations.AddField(
            model_name='schedule',
            name='payroll_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='payroll_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
