# Generated by Django 4.2.5 on 2025-03-23 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ntax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vacationleave', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sickleave', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
