# Generated by Django 4.2.5 on 2025-03-25 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField()),
                ('generated_at', models.DateTimeField()),
                ('is_protected', models.BooleanField(default=True)),
                ('payroll_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
