# Generated by Django 4.2.5 on 2025-03-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
