# Generated by Django 4.2.5 on 2025-04-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0002_alter_payslip_approved_at_alter_payslip_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
