# Generated by Django 4.2.5 on 2025-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('expected_hours', models.IntegerField()),
            ],
        ),
    ]
