# Generated by Django 4.2.5 on 2025-03-25 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('totalovertime', '0004_totalovertime_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deductions', '0001_initial'),
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_date', models.DateField()),
                ('deductions_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deductions.deductions')),
                ('earnings_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='earnings.earnings')),
                ('overtime_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='totalovertime.totalovertime')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
