# Generated by Django 4.2.5 on 2025-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='permissions',
            field=models.CharField(max_length=255),
        ),
    ]
