# Generated by Django 4.2.5 on 2025-03-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_summary', '0001_initial'),
        ('overtimebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regularot', models.IntegerField()),
                ('regularholiday', models.IntegerField()),
                ('specialholiday', models.IntegerField()),
                ('restday', models.IntegerField()),
                ('nightdiff', models.IntegerField()),
                ('backwage', models.IntegerField()),
                ('attendancesummary_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_summary.attendancesummary')),
            ],
        ),
    ]
