# Generated by Django 4.2.5 on 2025-04-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='regularholiday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='specialholiday',
            field=models.IntegerField(null=True),
        ),
    ]
