# Generated by Django 4.2.5 on 2025-03-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='pagibig_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.pagibig'),
        ),
        migrations.AddField(
            model_name='salary',
            name='philhealth_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.philhealth'),
        ),
        migrations.AddField(
            model_name='salary',
            name='sss_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.sss'),
        ),
    ]
